import HeroSection from "./HeroSection";
import PropertyCard from "./PropertyCard";
import PropertyGrid from "./PropertyGrid";
import AgentCard from "./AgentCard";
import InquiryForm from "./InquiryForm";
import CompanyFeatures from "./CompanyFeatures";
import ContactSection from "./ContactSection";
import SearchBar from "./SearchBar";
import SaleHero from "./SaleHero";
import SaleProcess from "./SaleProcess";
import SaleInquiry from "./SaleInquiry";
import PromoBanner from "./PromoBanner";
import OfferDetail from "./OfferDetail";
import SearchResult from "./SearchResult";
import PropertyDetail from "./PropertyDetail";
import NewsFeed from "./NewsFeed";
import CompanyProfile from "./CompanyProfile";
import PropertyFilterBar from "./PropertyFilterBar";
import NeighborhoodCard from "./NeighborhoodCard";
import AccessCard from "./AccessCard";
import PropertySlider from "./PropertySlider";
import StreetViewCard from "./StreetViewCard";
import MapCard from "./MapCard";
import PropertyTable from "./PropertyTable";
import { EstateProvider } from "./contexts/EstateContext";

// Map for ComponentsProvider
export const EstateComponents = {
  HeroSection,
  PropertyCard,
  PropertyGrid,
  AgentCard,
  InquiryForm,
  CompanyFeatures,
  ContactSection,
  SearchBar,
  SaleHero,
  SaleProcess,
  SaleInquiry,
  PromoBanner,
  OfferDetail,
  SearchResult,
  PropertyDetail,
  NewsFeed,
  CompanyProfile,
  EstateProvider,
  PropertyFilterBar,
  NeighborhoodCard,
  AccessCard,
  PropertySlider,
  StreetViewCard,
  MapCard,
  PropertyTable,
};

// Map for componentPropsProvider
export const EstateDefaultProps = {
  HeroSection: {
    _componentDesc: "Full-width hero with background image and search",
    title: "Find Your Dream Home",
    subtitle: "Discover the perfect property in the best locations.",
    backgroundImage:
      "https://images.unsplash.com/photo-1600596542815-6ad4c1277855?ixlib=rb-4.0.3&auto=format&fit=crop&w=1920&q=80",
    showSearch: true,
  },
  PropertyCard: {
    _componentDesc: "Individual property listing card",
    id: "property-card-preview",
    image:
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    price: "$850,000",
    address: "123 Palm Avenue, Beverly Hills, CA 90210",
    itemId: "property-card-preview",
    beds: 3,
    baths: 2,
    sqft: 2400,
    tag: "FOR SALE",
  },
  PropertyGrid: {
    _componentDesc: "Grid layout of property cards.",
    title: "Featured Properties",
    description: "Explore our latest listings chosen for you.",
    columns: 3,
    layout: "grid",
    selectedPropertyIdKey: "estate.selectedPropertyId",
    keywordKey: "estate.keyword",
    intentKey: "estate.filter.intent",
    properties: [
      {
        id: "property-sakura-terrace",
        itemId: "property-sakura-terrace",
        image:
          "https://images.unsplash.com/photo-1600596542815-6ad4c1277855?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        price: "¥58,000,000",
        address: "東京都世田谷区桜新町2-14-12",
        building_name: "サクラテラス世田谷",
        buildingName: "サクラテラス世田谷",
        nearest_station: "桜新町駅 徒歩7分",
        nearestStation: "桜新町駅 徒歩7分",
        floor_plan: "3LDK",
        floorPlan: "3LDK",
        floor_area: 72.4,
        areaSize: "72.4㎡",
        year_built: 2018,
        yearBuilt: "2018年",
        tag: "売買",
        property_type: "sale",
        transport_info: "桜新町駅 徒歩7分",
        pets_allowed: false,
        features: ["オートロック", "宅配ボックス", "南向き"],
      },
      {
        id: "property-riverside-nakameguro",
        itemId: "property-riverside-nakameguro",
        image:
          "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        price: "¥165,000 / 月",
        address: "東京都目黒区中目黒3-5-1",
        building_name: "リバーサイド中目黒",
        buildingName: "リバーサイド中目黒",
        nearest_station: "中目黒駅 徒歩6分",
        nearestStation: "中目黒駅 徒歩6分",
        floor_plan: "1LDK",
        floorPlan: "1LDK",
        floor_area: 42.8,
        areaSize: "42.8㎡",
        year_built: 2021,
        yearBuilt: "2021年",
        tag: "賃貸",
        property_type: "rent",
        transport_info: "中目黒駅 徒歩6分",
        pets_allowed: true,
        petsAllowed: true,
        features: ["ペット可", "宅配ボックス", "エアコン完備"],
      },
      {
        id: "property-ark-view-akasaka",
        itemId: "property-ark-view-akasaka",
        image:
          "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        price: "¥320,000,000",
        address: "東京都港区赤坂4-8-5",
        building_name: "アークビュー赤坂",
        buildingName: "アークビュー赤坂",
        nearest_station: "赤坂駅 徒歩4分",
        nearestStation: "赤坂駅 徒歩4分",
        floor_plan: "投資用",
        floorPlan: "投資用",
        floor_area: 118.2,
        areaSize: "118.2㎡",
        year_built: 2014,
        yearBuilt: "2014年",
        tag: "投資",
        property_type: "investment",
        transport_info: "赤坂駅 徒歩4分",
        features: ["管理良好", "駅近", "高利回り"],
      },
    ],
    __interactions: [
      {
        id: "estate-grid-select",
        event: "estate:property:selected",
        action: "set-shared-state",
        targetPath: "estate.selectedPropertyId",
        valueFrom: "$.id",
      },
    ],
  },
  AgentCard: {
    _componentDesc: "Real estate agent profile card",
    name: "Sarah Johnson",
    title: "Senior Real Estate Agent",
    image:
      "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    phone: "+1 (555) 123-4567",
    email: "sarah@example.com",
    bio: "Specializing in luxury properties with over 10 years of experience in the local market.",
  },
  InquiryForm: {
    _componentDesc: "Contact form for property inquiries",
    title: "Interested in this property?",
    submitLabel: "Send Message",
    selectedPropertyIdKey: "estate.selectedPropertyId",
    __interactions: [
      {
        id: "estate-inquiry-submit",
        event: "estate:inquiry:submitted",
        action: "set-shared-state",
        targetPath: "estate.lastInquiry",
        valueFrom: "$",
      },
    ],
  },
  CompanyFeatures: {
    _componentDesc: "Company features and benefits section",
    title: "当社の強み",
    subtitle:
      "お客様満足度を最優先に、不動産に関するワンストップサービスを提供しています。",
  },
  ContactSection: {
    _componentDesc: "Company contact information card",
    companyName: "Estate Realty Group",
    address: "123 Business Blvd, Suite 100, City, ST 12345",
    phone: "+1 (800) 123-4567",
    email: "contact@estate-realty.com",
  },
  SearchBar: {
    _componentDesc: "Inline search input with button",
    placeholder: "Search by location, price, or keyword...",
    buttonLabel: "Search",
    keywordKey: "estate.keyword",
    searchableFields: [
      "address",
      "building_name",
      "city",
      "ward",
      "prefecture",
      "nearest_station",
      "transport_info",
      "floor_plan",
      "layout_description",
      "price",
      "tag",
      "transport",
      "areaSize",
      "expectedRent",
      "yearBuilt",
      "features",
    ],
    __interactions: [
      {
        id: "estate-search-state",
        event: "estate:search:changed",
        action: "set-shared-state",
        targetPath: "estate.keyword",
        valueFrom: "$.keyword",
      },
      {
        id: "estate-search-event",
        event: "estate:search:changed",
        action: "emit-event",
        targetPath: "estate:search:changed",
        valueFrom: "$",
      },
    ],
  },
  SaleHero: {
    _componentDesc: "Sell your home hero section with CTA",
    title: "Sell Your Home for the Best Price",
    subtitle:
      "Expert valuation, marketing strategies, and support to get you the best deal.",
    ctaText: "Get Free Assessment",
    backgroundImage:
      "https://images.unsplash.com/photo-1560518883-ce09059eeffa?ixlib=rb-4.0.3&auto=format&fit=crop&w=1920&q=80",
  },
  SaleProcess: {
    _componentDesc: "Step-by-step selling process",
    title: "How It Works",
    subtitle: "Our simple 4-step process to sell your home.",
  },
  SaleInquiry: {
    _componentDesc: "Property valuation request form",
    title: "Request a Free Property Valuation",
    description:
      "Fill out the form below and we will get back to you with a comprehensive market analysis.",
    submitLabel: "Get My Valuation",
  },
  PromoBanner: {
    _componentDesc: "Promotional banner with call-to-action",
    title: "Special Offer",
    text: "Contact us today for a free consultation and get 50% off your listing fee!",
    buttonLabel: "Learn More",
    backgroundColor: "#1e3a8a",
  },
  OfferDetail: {
    _componentDesc: "Promotional offer detail with terms",
    title: "50% Off Listing Fee",
    description:
      "For a limited time, we are offering a 50% discount on our standard listing fee for new clients who sign up for our premium selling package. This includes professional photography, 3D tours, and featured listings on major real estate platforms.",
    terms: [
      "Valid for new clients only.",
      "Must sign an exclusive right-to-sell agreement.",
      "Property must be located within our service area.",
      "Cannot be combined with other offers.",
    ],
    code: "SAVE50",
    expirationDate: "2025-12-31",
  },
  SearchResult: {
    _componentDesc: "Search results grid with count header",
    title: "Search Results",
    totalCount: 0,
    keywordKey: "estate.keyword",
    selectedPropertyIdKey: "estate.selectedPropertyId",
    results: [
      {
        id: "search-sakura-terrace",
        itemId: "search-sakura-terrace",
        image:
          "https://images.unsplash.com/photo-1600596542815-6ad4c1277855?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        price: "¥58,000,000",
        address: "東京都世田谷区桜新町2-14-12",
        building_name: "サクラテラス世田谷",
        buildingName: "サクラテラス世田谷",
        nearest_station: "桜新町駅 徒歩7分",
        nearestStation: "桜新町駅 徒歩7分",
        floor_plan: "3LDK",
        floorPlan: "3LDK",
        floor_area: 72.4,
        areaSize: "72.4㎡",
        year_built: 2018,
        yearBuilt: "2018年",
        tag: "売買",
        property_type: "sale",
        features: ["オートロック", "宅配ボックス", "南向き"],
      },
      {
        id: "search-riverside-nakameguro",
        itemId: "search-riverside-nakameguro",
        image:
          "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        price: "¥165,000 / 月",
        address: "東京都目黒区中目黒3-5-1",
        building_name: "リバーサイド中目黒",
        buildingName: "リバーサイド中目黒",
        nearest_station: "中目黒駅 徒歩6分",
        nearestStation: "中目黒駅 徒歩6分",
        floor_plan: "1LDK",
        floorPlan: "1LDK",
        floor_area: 42.8,
        areaSize: "42.8㎡",
        year_built: 2021,
        yearBuilt: "2021年",
        tag: "賃貸",
        property_type: "rent",
        petsAllowed: true,
        features: ["ペット可", "宅配ボックス", "エアコン完備"],
      },
      {
        id: "search-ark-view-akasaka",
        itemId: "search-ark-view-akasaka",
        image:
          "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        price: "¥320,000,000",
        address: "東京都港区赤坂4-8-5",
        building_name: "アークビュー赤坂",
        buildingName: "アークビュー赤坂",
        nearest_station: "赤坂駅 徒歩4分",
        nearestStation: "赤坂駅 徒歩4分",
        floor_plan: "投資用",
        floorPlan: "投資用",
        floor_area: 118.2,
        areaSize: "118.2㎡",
        year_built: 2014,
        yearBuilt: "2014年",
        tag: "投資",
        property_type: "investment",
        features: ["管理良好", "駅近", "高利回り"],
      },
    ],
  },
  PropertyDetail: {
    _componentDesc: "Detailed property information view",
    title: "物件詳細",
    description: "選択された物件の詳細情報をご確認いただけます。",
    buildingName: "ファミニューナ大森南",
    image:
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    priceJPY: "5,800万円",
    price_jpy: "5,800万円",
    addressJP: "東京都渋谷区神宮前 5-12-8",
    address_jp: "東京都渋谷区神宮前 5-12-8",
    latitude: 35.6654,
    longitude: 139.7098,
    tagJP: "売買物件",
    tag_jp: "売買物件",
    propertyType: "sale",
    property_type: "sale",
    areaSqm: "78.4㎡",
    area_sqm: "78.4㎡",
    tsubo: "23.7坪",
    floorPlan: "3LDK",
    floor_plan: "3LDK",
    yearBuiltJP: "2018年3月",
    year_built_jp: "2018年3月",
    transport: "東京メトロ 渋谷駅 徒歩8分",
    transport_info: "東京メトロ 渋谷駅 徒歩8分",
    deposit: "100万円",
    keyMoney: "50万円",
    managementFee: "1.5万円/月",
    maintenanceFee: "8,000円/月",
    yieldValue: "4.2%",
    petsAllowed: "相談",
    pets_allowed: "相談",
    landRight: "所有権",
    land_right: "所有権",
    itemIdKey: "id",
    selectedPropertyIdKey: "estate.selectedPropertyId",
    galleryImages: [
      {
        id: "detail-gallery-main",
        src: "https://images.unsplash.com/photo-1600585152220-90363fe7e115?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
        title: "外観",
        caption: "建物の全景を確認できます。",
      },
      {
        id: "detail-gallery-floorplan",
        src: "https://images.unsplash.com/photo-1522698531939-7e5f5c7d3b1c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
        title: "間取り図",
        caption: "室内導線とレイアウトを確認できます。",
      },
      {
        id: "detail-gallery-room",
        src: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
        title: "室内写真",
        caption: "居室の雰囲気を確認できます。",
      },
    ],
    hazardMapUrl: "https://www.gsi.go.jp/bousaichiri/hazardmap.html",
    nearbyStores: "オーケーストア大森南店 / マルエツ大森町店",
    nearbyHospitals: "大森赤十字病院 / 東京労災病院",
    nearbySchools: "大田区立大森第一小学校 / 大森第四中学校",
    nearbyParks: "大森ふるさとの浜辺公園 / 平和の森公園",
    neighborhoodSummary: "周辺は生活利便施設が整っており、通勤と子育てのバランスを取りやすいエリアです。",
    features: [
      "南向きで日当たり良好",
      "システムキッチン（IH・食洗機付）",
      "浴室乾燥機付き",
      "宅配ボックス完備",
    ],
  },
  NewsFeed: {
    _componentDesc: "Latest news and updates feed",
    title: "お知らせ",
    description: "最新の情報をお届けします。",
    maxItems: 5,
  },
  CompanyProfile: {
    _componentDesc: "Company information page",
    title: "会社案内",
    description: "当社についてご紹介いたします。",
    presidentName: "代表取締役 山田 太郎",
    presidentTitle: "代表取締役社長",
    presidentMessage: "私たちは、お客様一人ひとりの理想の住まい探しをサポートします。不動産取引における透明性と誠実さを何より大切にし、専門知識と豊富な経験を活かして、最適な物件選びから購入後のアフターサービスまで一貫したサポートを提供いたします。\n\n地域に密着した不動産会社として、お客様の人生の大切な決断を全力でサポートしてまいります。",
    companyName: "株式会社Think Estate",
    address: "〒123-4567 東京都世田谷区xxx町1-2-3",
    phone: "03-1234-5678",
    fax: "03-1234-5679",
    email: "info@thinkestate-jp.com",
    representative: "山田 太郎",
    establishmentDate: "2010年4月",
    capital: "1,000万円",
    businessDescription: "不動産売買・賃貸仲介、不動産管理、不動産コンサルティング",
    license: "東京都知事 (1) 第12345号",
    employees: "15名（2024年4月現在）",
    history: [
      { year: "2010", month: "4", event: "東京都世田谷区にて株式会社Think Estateを設立" },
      { year: "2012", month: "6", event: "賃貸管理事業を開始" },
      { year: "2015", month: "3", event: "売買仲介事業に参入" },
      { year: "2018", month: "9", event: "東京都知事免許 (1) 第12345号 取得" },
      { year: "2020", month: "1", event: "不動産コンサルティング事業を開始" },
      { year: "2023", month: "4", event: "ウェブサイトをリニューアル" },
    ],
    mapEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3240.123456789!2d139.123456789!3d35.123456789!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0000000000000000%3A0x0000000000000000!2zMemzrQ!5e0!3m2!1sja!2sjp!4v1234567890",
  },
  PropertyFilterBar: {
    _componentDesc: "Filter bar for property listings",
    title: "Browse properties",
    description: "Filter by keyword, station, floor plan, area, year built, and pets, then narrow the list further by intent.",
    intentKey: "estate.filter.intent",
    keywordKey: "estate.keyword",
    activeIntent: "all",
    activeKeyword: "",
  },
  NeighborhoodCard: {
    _componentDesc: "Neighborhood information card",
    title: "Neighborhood guide",
    description: "A calm area summary for the selected property with nearby points of interest.",
    selectedPropertyIdKey: "estate.selectedPropertyId",
    items: [
      { id: "prop-1", kind: "sale", title: "Shibuya Residence", locationLabel: "Shibuya, Tokyo" },
      { id: "prop-2", kind: "rent", title: "Nakameguro Loft", locationLabel: "Nakameguro, Tokyo" },
    ],
  },
  AccessCard: {
    _componentDesc: "Access and location information card",
    title: "Access and location",
    description: "Street view, map, and quick property context in one calm panel.",
    selectedPropertyIdKey: "estate.selectedPropertyId",
    items: [
      { id: "prop-1", kind: "sale", title: "Shibuya Residence", locationLabel: "Shibuya, Tokyo", locationSpotId: "spot-shibuya" },
    ],
    spots: [
      { id: "spot-shibuya", kind: "streetview", locationLabel: "Shibuya Crossing, Tokyo", viewpoint: "35.6595,139.7005", heading: 175, pitch: 8, fov: 75 },
    ],
  },
  PropertySlider: {
    _componentDesc: "Horizontal property card slider",
    title: "Property slider",
    description: "Horizontal premium cards for featured homes and rentals.",
    detailPageId: "page-estate-detail",
    selectedPropertyIdKey: "estate.selectedPropertyId",
    slides: [
      {
        id: "slide-sakura-terrace",
        kind: "sale",
        title: "サクラテラス世田谷",
        summary: "駅近・築浅の3LDK",
        price: "¥58,000,000",
        area: "72.4㎡",
        rooms: "3LDK",
        status: "売買",
        image:
          "https://images.unsplash.com/photo-1600596542815-6ad4c1277855?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        locationLabel: "桜新町駅 徒歩7分",
      },
      {
        id: "slide-riverside-nakameguro",
        kind: "rent",
        title: "リバーサイド中目黒",
        summary: "ペット可の1LDK",
        price: "¥165,000 / 月",
        area: "42.8㎡",
        rooms: "1LDK",
        status: "賃貸",
        image:
          "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        locationLabel: "中目黒駅 徒歩6分",
      },
      {
        id: "slide-ark-view-akasaka",
        kind: "investment",
        title: "アークビュー赤坂",
        summary: "投資向けの都心物件",
        price: "¥320,000,000",
        area: "118.2㎡",
        rooms: "投資用",
        status: "投資",
        image:
          "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        locationLabel: "赤坂駅 徒歩4分",
      },
    ],
  },
  StreetViewCard: {
    _componentDesc: "Street view preview card",
    title: "Neighborhood Street View",
    subtitle: "Preview the surroundings for the selected property before a viewing.",
    viewpoint: "35.6595,139.7005",
    heading: 175,
    pitch: 8,
    fov: 75,
    locationLabel: "Shibuya, Tokyo",
  },
  MapCard: {
    _componentDesc: "Location map card",
    title: "Location Map",
    subtitle: "Check the neighborhood map before booking a showing.",
    center: "35.6595,139.7005",
    zoom: 16,
    locationLabel: "Shibuya, Tokyo",
  },
  PropertyTable: {
    _componentDesc: "Property listing table",
    columns: "address,property_type,floor_plan,floor_area,price_sale,price_rent_monthly,nearest_station,year_built",
    loading: false,
    properties: [
      {
        id: "table-sakura-terrace",
        status: "published",
        property_type: "sale",
        address: "東京都世田谷区桜新町2-14-12",
        building_name: "サクラテラス世田谷",
        floor_plan: "3LDK",
        floor_area: 72.4,
        price_sale: 58000000,
        nearest_station: "桜新町駅 徒歩7分",
        year_built: 2018,
        features: ["オートロック", "宅配ボックス"],
      },
      {
        id: "table-riverside-nakameguro",
        status: "published",
        property_type: "rent",
        address: "東京都目黒区中目黒3-5-1",
        building_name: "リバーサイド中目黒",
        floor_plan: "1LDK",
        floor_area: 42.8,
        price_rent_monthly: 165000,
        nearest_station: "中目黒駅 徒歩6分",
        year_built: 2021,
        pets_allowed: true,
        features: ["ペット可", "宅配ボックス"],
      },
      {
        id: "table-ark-view-akasaka",
        status: "published",
        property_type: "investment",
        address: "東京都港区赤坂4-8-5",
        building_name: "アークビュー赤坂",
        floor_plan: "投資用",
        floor_area: 118.2,
        price_sale: 320000000,
        nearest_station: "赤坂駅 徒歩4分",
        year_built: 2014,
        expected_yield: 4.2,
        features: ["管理良好", "駅近", "高利回り"],
      },
    ],
  },
};

export { EstateProvider };

// API client layer
export * from './api';
// Re-export types for external consumers
export type {
  EstateProperty,
  EstatePropertyPost,
  EstatePropertyTag,
  EstatePropertyMedia,
  EstatePropertyMediaAsset,
  PropertySearchFilters,
  GhostApiResponse,
  GhostPagination,
} from './types/property';
export type {
  EstateInquiry,
  EstateInquiryInput,
} from './types/inquiry';
